project:
  type: website
  output-dir: docs

website:
  title: "David Lloyd George"
  navbar:
    left: 
      - about.qmd
      - projects.qmd
    right:
      - icon: github
        href: https://github.com/dlloydgeorge
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



