project:
  type: website
  output-dir: docs

website:
  title: "David Lloyd George"
  navbar:
    left: 
      - href: about.qmd
        text: About
      - href: projects/index.qmd
        text: Projects
    right:
      - icon: github
        href: https://github.com/dlloydgeorge

collections:
  projects: 
    categories: true

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



